### PR TITLE
changed regex to match SHA256 instead of SHA1 in ETag header

### PR DESCRIPTION
**Pull request by gerrit8143**
#47

### CODE REVIEW

**Comment by bgagnon** [comment]
The previous ETag signature was indeed a SHA1, but the important part was that it happened to be the Git commit SHA1. The new ETag signature is a SHA256 _of something_, but what?

@gerrit8143 have you verified that his is a Git SHA256, as explained in the [hash function transition plan](https://github.com/git/git/blob/master/Documentation/technical/hash-function-transition.txt) ?

**Comment by bgagnon** [comment]
See issue #46

**Comment by gerrit8143** [comment]
> The previous ETag signature was indeed a SHA1, but the important part was that it happened to be the Git commit SHA1. The new ETag signature is a SHA256 _of something_, but what?
> 
> @gerrit8143 have you verified that his is a Git SHA256, as explained in the [hash function transition plan](https://github.com/git/git/blob/master/Documentation/technical/hash-function-transition.txt)?

@bgagnon sorry, no i didn't verify that, i just tested the change with:

`jb install github.com/coreos/kube-prometheus/jsonnet/kube-prometheus/`

 and it worked again

**Comment by bgagnon** [comment]
@gerrit8143 does it work on a subsequent `jb install` from a `jsonnetfile.json` with that SHA256 in it?

In #49 I change the strategy to no longer rely on the ETag at all and using `git ls-remote` instead.

**Comment by bgagnon** [comment]
Superseded by #49. Closing.

@gerrit8143 I don't think this solves all issues from #47, so I am leaving that issue open

**Pull request closed without merging**
