### PR TITLE
Introduce kingpin as CLI helper library

### LINKED ISSUE #4: panic: runtime error: slice bounds out of range
```
$ jb
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.Main(0xc420078058)
	/Users/twilkie/Documents/src/github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb/main.go:71 +0x255
main.main()
	/Users/twilkie/Documents/src/github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb/main.go:202 +0x22
```

### PR DESCRIPTION
**Pull request by metalmatze**
There is probably a lot more room for improvement.
But this should do the trick for now.

Fixes #4

### CODE REVIEW

**Comment by brancz** [comment]
Would you mind adding this dependency as well as the existing one with `dep`? Just to make sure this stays go gettable.

**Comment by metalmatze** [comment]
Sure, I wasn't really sure. I'd brought up the issue afterwards. To keep it `go get`able you want me to commit `vendor/` too?

**Comment by brancz** [comment]
> Sure, I wasn't really sure. I'd brought up the issue afterwards. To keep it go getable you want me to commit vendor/ too?

exactly

**Comment by metalmatze** [comment]
Done.

**Comment by brancz** [comment]
Thanks! :+1: lgtm

**Pull request merged**
