### PR TITLE
Stable transitive dependencies

### LINKED ISSUE #160: `jb update` with transitive diamond shaped dependencies is not deterministic
`jb update` (and `jb install` without lockfile) fetches transitive dependency versions non deterministically.

We have a one or two instance where we currently have diamond shaped transitive dependencies.
While I know diamond shaped dependencies are not really supported I expect to either get the first or last version of
the dependency seen.

Currently the version the bundler fetches is determined randomly.

## Additional Context

The dependencies are returned in a map with the name as the key

https://github.com/jsonnet-bundler/jsonnet-bundler/blob/76754ada90a2cbe773a667f9629a9d0eb8fb925b/spec/v1/spec.go#L30

And then looped over in `ensure`

https://github.com/jsonnet-bundler/jsonnet-bundler/blob/76754ada90a2cbe773a667f9629a9d0eb8fb925b/pkg/packages.go#L216

Maps can't be iterated over in a deterministic manner in Go. This effectively chooses a random version.

This seems to be mitigated somewhat by the [deduplication process while loading the file](https://github.com/jsonnet-bundler/jsonnet-bundler/blob/76754ada90a2cbe773a667f9629a9d0eb8fb925b/spec/v1/spec.go#L63) but it does not work if two dependencies require the same dependency.

### Bundler Resolution Process

https://github.com/jsonnet-bundler/jsonnet-bundler/issues/112#issuecomment-636091859

## Expected Behavior

Lockfile stays stable after successive `jb update`.

## Behavior

Lockfile changes randomly.

## Steps To Reproduce

```sh
mkdir a b

cat > a/jsonnetfile.json <<DEPS
{
    "dependencies": [
        {
            "source": {
                "git": {
                    "remote": "https://github.com/prometheus-operator/kube-prometheus.git",
                    "subdir": "jsonnet/kube-prometheus"
                }
            },
            "version": "fbbfff8f377207d06aca4d84630acd6270c23b54"
        }
    ],
    "legacyImports": true,
    "version": 1
}
DEPS

cat > b/jsonnetfile.json <<DEPS
{
    "dependencies": [
        {
            "source": {
                "git": {
                    "remote": "https://github.com/prometheus-operator/kube-prometheus.git",
                    "subdir": "jsonnet/kube-prometheus"
                }
            },
            "version": "42ea595d60265b803ad460a971a7186488f6be7e"
        }
    ],
    "legacyImports": true,
    "version": 1
}
DEPS

cat > jsonnetfile.json <<DEPS
{
    "dependencies": [
        {
            "source": {
                "local": {
                    "directory": "a"
                }
            }
        },
        {
            "source": {
                "local": {
                    "directory": "b"
                }
            }
        }
    ],
    "legacyImports": true,
    "version": 1
}
DEPS


jb install
for i in {1..10}
do
  jb update
  cp jsonnetfile.lock.json jsonnetfile.lock.json-$(date --rfc-3339=s | tr ' ' 'T')
done

sha256sum jsonnetfile.lock.json-* | sort -u -k1,1
# 5a94db31d2fe7644fef9db7199bbb5614c69367bd242ceeb8f04b45a6777bb2a  jsonnetfile.lock.json-2022-06-02T08:54:13+02:00
# f117b635cb258552fc13b5f3c625461587795bf14b299b9e3e2113d275c2aa07  jsonnetfile.lock.json-2022-06-02T08:55:04+02:00

git diff --no-index jsonnetfile.lock.json-2022-06-02T08:54:13+02:00 jsonnetfile.lock.json-2022-06-02T08:55:04+02:00
# [...]
# -      "version": "d039275e4916aceae1c137120882e01d857787ac",
# -      "sum": "515vMn4x4tP8vegL4HLW0nDO5+njGTgnDZB5OOhtsCI="
# +      "version": "199e363523104ff8b3a12483a4e3eca86372b078",
# +      "sum": "/jDHzVAjHB4AOLkJHw1GyATX5ogZ1iMdcJXZAgaG3+g="
# [...]
```

### PR DESCRIPTION
**Pull request by bastjan**
This PR fixes #160 by tracking the order of dependencies in an [OrderedMap](https://github.com/elliotchance/orderedmap).

- This PR requires Go 1.18+ because of generic type support for the `OrderedMap`. The two most recent Go versions now both support generics.

Question still open from my site / notes for the reviewer:
- This PR breaks the type definition of `github.com/jsonnet-bundler/jsonnet-bundler/spec/v1.JsonnetFile`.
   Is this acceptable or should the ordered dependencies be tracked in an additional struct member and the `Dependencies` map be deprecated?
- Ordering the dependencies by name should no longer be necessary https://github.com/bastjan/jsonnet-bundler/blob/1bc175909e3632db7649c612a6b43f770a518ca8/spec/v1/spec.go#L83 . Should it be removed?

### CODE REVIEW

**Comment by metalmatze** [comment]
Thank you for the work. I'm not sure we need to pull in that third-party OrderedMap though. :thinking: 
Shouldn't it be possible to do the same without generics? If I'm not mistaken the `deps.Dependency` should be the only object passed into that container, in which case making that ordered should be possible too.

**Comment by 7840vz** [comment]
Hi! Is this something that could be merged?  Or only if reimplemented without deps.Dependency?

**Comment by bastjan** [comment]
Hi @metalmatze @Mewjaden,

I'm still interested in upstreaming this issue. Should I reimplement the OrderedMap functionality (array with some helper functions, will be slightly less performant) or is the dependency fine?

**Comment by metalmatze** [comment]
Honestly, if we can get it to work as is maybe we should just go for it. It's been some time... Sorry. 
Can you rebase and see if that fixes CI? Thanks!

**Comment by bastjan** [comment]
I rebased the PR. I think the github workflow still references Go versions without generics. Are those still needed?

We use this change in production since i implemented it (together with some changes to parallelize fetching of dependencies).

**Comment by metalmatze** [comment]
No objections. Let's update the Go version to the lastest three versions.

**Comment by metalmatze** [comment]
I can't seem to push to your PR to update the Go versions. 
Here's my patch. 

The `.drone.yml` gets generated with the [drone CLI](https://docs.drone.io/cli/install/) with this command: `drone jsonnet --format yaml`.


```diff
diff --git a/.drone.jsonnet b/.drone.jsonnet
index 56543ed..3053cf8 100644
--- a/.drone.jsonnet
+++ b/.drone.jsonnet
@@ -39,8 +39,9 @@
       ],
     },
 
-    build('1.18'),
-    build('1.19'),
+    build('1.21'),
+    build('1.22'),
+    build('1.23'),
 
     golang() {
       name: 'generate',
diff --git a/.drone.yml b/.drone.yml
index a8aeb97..d8605b1 100644
--- a/.drone.yml
+++ b/.drone.yml
@@ -24,8 +24,8 @@ steps:
   environment:
     CGO_ENABLED: "0"
     GO111MODULE: "on"
-  image: golang:1.18
-  name: build-1.18
+  image: golang:1.21
+  name: build-1.21
   pull: always
   when:
     event:
@@ -38,8 +38,22 @@ steps:
   environment:
     CGO_ENABLED: "0"
     GO111MODULE: "on"
-  image: golang:1.19
-  name: build-1.19
+  image: golang:1.22
+  name: build-1.22
+  pull: always
+  when:
+    event:
+      exclude:
+      - tag
+- commands:
+  - make build
+  - make test
+  - make test-integration
+  environment:
+    CGO_ENABLED: "0"
+    GO111MODULE: "on"
+  image: golang:1.23
+  name: build-1.23
   pull: always
   when:
     event:

```

**Comment by metalmatze** [comment]
Huh. Seems like we moved to GitHub actions a year ago (and it seems like I merged the PR and forgot). I'll remove the drone configs then. 
Thanks for updating!

**Review by metalmatze — APPROVED** [review]

**Comment by metalmatze** [comment]
Thank you so much for bearing with us!

**Comment by bastjan** [comment]
Thanks for the review and merging this PR 🥳

**Pull request merged**
